### ISSUE TITLE
Charts not available

### ISSUE THREAD

**Issue by kerbs-ns** [dniccum/nova-webhooks#15]
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.<anonymous> (nova-apex-chart:2:582805)
    at Fn (runtime-core.esm-bundler.js:888:44)
    at we.fn (runtime-core.esm-bundler.js:5600:57)
    at we.run (reactivity.esm-bundler.js:185:25)
    at R.e.update (runtime-core.esm-bundler.js:5714:56)
    at R (runtime-core.esm-bundler.js:5728:9)
    at j (runtime-core.esm-bundler.js:5510:9)
    at N (runtime-core.esm-bundler.js:5468:17)
    at g (runtime-core.esm-bundler.js:5058:21)
    at we.fn (runtime-core.esm-bundler.js:5607:21)

**Comment by jansgescheit** [comment]
Should be fixed with https://github.com/coroo/nova-chartjs/releases/tag/v0.4.0
